version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: com.github.spotbugs:spotbugs
        versions: "[4.9.0,)"
      - dependency-name: com.github.spotbugs:spotbugs-annotations
        versions: "[4.9.0,)"
      - dependency-name: org.junit.jupiter:junit-jupiter-api
        versions: "[6.0.0,)"
      - dependency-name: org.junit.jupiter:junit-jupiter-engine
        versions: "[6.0.0,)"
      - dependency-name: org.mockito:mockito-core
        versions: "[5.0.0,)"
      - dependency-name: org.mockito:mockito-inline
        versions: "[5.0.0,)"
