name: Merge on Approval
on:
  pull_request_review:
    types:
      - submitted
      - edited
  workflow_run:
    workflows:
      - push-and-pull_request
    types:
      - completed

jobs:
  merge:
    name: Merge
    if: ${{ !github.event.review || github.event.review.state == 'approved' }}
    runs-on: ubuntu-latest
    steps:
      - uses: reitermarkus/automerge@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
